codecov:
  max_report_age: off
  branch: main
coverage:
  status:
    patch:
      default:
        threshold: 10%
ignore:
  - ./hessian-adapters/**/*
  - ./hessian-rpc/**/*
  - ./hessian-services/**/*
  - ./test/**/*
