name: Coverage

on:
  schedule:
    - cron: "0 16 * * *"
  workflow_dispatch:  

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          ref: main 

      - name: Set up JDK 11
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 11

      - name: Run tests with coverage
        run: ./mvnw -B clean verify --file pom.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./hessian2-codec/target/site/jacoco/jacoco.xml
          flags: main-branch
          branch: main
          fail_ci_if_error: true
          verbose: true
      - name: Upload to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./hessian2-codec/target/site/jacoco/jacoco.xml
