name: Coverage

on:
  schedule:
    - cron: "0 16 * * *"

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          ref: main 

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11

      - name: Run tests with coverage
        run: ./mvnw -B clean verify --file pom.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./hessian2-codec/target/site/jacoco/jacoco.xml
          flags: hessian2-codec
